# Generated by Django 3.1.1 on 2020-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='CreateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('question_1', models.CharField(blank=True, max_length=50, null=True)),
                ('question_2', models.CharField(blank=True, max_length=50, null=True)),
                ('question_3', models.CharField(blank=True, max_length=50, null=True)),
                ('question_4', models.CharField(blank=True, max_length=50, null=True)),
                ('question_5', models.CharField(blank=True, max_length=50, null=True)),
                ('question_6', models.CharField(blank=True, max_length=50, null=True)),
                ('question_7', models.CharField(blank=True, max_length=50, null=True)),
                ('question_8', models.CharField(blank=True, max_length=50, null=True)),
                ('question_9', models.CharField(blank=True, max_length=50, null=True)),
                ('question_10', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement1', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement2', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement3', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement4', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement5', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement6', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement7', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement8', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement9', models.CharField(blank=True, max_length=50, null=True)),
                ('requirement10', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'CreateJob',
            },
        ),
    ]
