# Generated by Django 3.1.4 on 2021-05-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createjob',
            name='question_11',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_12',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_13',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_14',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_15',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_16',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_17',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_18',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_19',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='question_20',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement1',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement10',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement11',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement12',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement13',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement14',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement15',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement2',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement3',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement4',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement5',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement6',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement7',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement8',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='requirement9',
        ),
    ]
