# Generated by Django 3.1.1 on 2020-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
