# Generated by Django 3.1.1 on 2020-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201210_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
