# Generated by Django 3.1.4 on 2021-05-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210515_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='question_11',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_12',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_13',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_14',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_15',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_16',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_17',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_18',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_19',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_20',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_1',
            field=models.CharField(blank=True, default='Please tell me about yourself.', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_10',
            field=models.CharField(blank=True, default='How do you explain new topics to coworkers unfamiliar with them?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_2',
            field=models.CharField(blank=True, default='What do you consider as your weakness?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_3',
            field=models.CharField(blank=True, default='What are your goals?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_4',
            field=models.CharField(blank=True, default='What are your actions if employees disagreed with your decision?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_5',
            field=models.CharField(blank=True, default='What can you do for us that other candidates cannot?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_6',
            field=models.CharField(blank=True, default='Describe a situation where results went against expectations. How did you adapt to this change?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_7',
            field=models.CharField(blank=True, default='Can you discuss a time where you had to manage your team through a difficult situation?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_8',
            field=models.CharField(blank=True, default='How do you prioritize your tasks when you have multiple deadlines to meet?', editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='question_9',
            field=models.CharField(blank=True, default='What is the most significant problem you solved in the workplace?', editable=False, max_length=250, null=True),
        ),
    ]
