# Generated by Django 3.1.1 on 2020-12-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_createjob_question_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createjob',
            old_name='answer',
            new_name='question_2',
        ),
    ]
