# Generated by Django 3.1.1 on 2020-12-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201214_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantID', models.IntegerField()),
            ],
            options={
                'db_table': 'currentApplicant',
            },
        ),
        migrations.CreateModel(
            name='currentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.IntegerField()),
            ],
            options={
                'db_table': 'currentJob',
            },
        ),
    ]
