# Generated by Django 3.1.1 on 2020-12-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20201209_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='question_10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='question_9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
