# Generated by Django 3.1.4 on 2021-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20210523_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='requirement1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement10',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='requirement9',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
