# Generated by Django 3.1.3 on 2020-12-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_joblist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createjob',
            old_name='id-answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='createjob',
            old_name='id-description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='createjob',
            old_name='id-question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='createjob',
            old_name='id-title',
            new_name='title',
        ),
    ]
