# Generated by Django 3.1.1 on 2020-12-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20201209_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createjob',
            name='question',
        ),
    ]
