# Generated by Django 3.1.1 on 2020-12-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20201209_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joblist',
        ),
    ]
