# Generated by Django 3.1.1 on 2020-12-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Applicant',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('emailAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'currentUser',
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.createjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applicant')),
            ],
            options={
                'db_table': 'SavedJobs',
            },
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.CharField(blank=True, max_length=250, null=True)),
                ('response_2', models.CharField(blank=True, max_length=250, null=True)),
                ('response_3', models.CharField(blank=True, max_length=250, null=True)),
                ('response_4', models.CharField(blank=True, max_length=250, null=True)),
                ('response_5', models.CharField(blank=True, max_length=250, null=True)),
                ('response_6', models.CharField(blank=True, max_length=250, null=True)),
                ('response_7', models.CharField(blank=True, max_length=250, null=True)),
                ('response_8', models.CharField(blank=True, max_length=250, null=True)),
                ('response_9', models.CharField(blank=True, max_length=250, null=True)),
                ('response_10', models.CharField(blank=True, max_length=250, null=True)),
                ('response_11', models.CharField(blank=True, max_length=250, null=True)),
                ('response_12', models.CharField(blank=True, max_length=250, null=True)),
                ('response_13', models.CharField(blank=True, max_length=250, null=True)),
                ('response_14', models.CharField(blank=True, max_length=250, null=True)),
                ('response_15', models.CharField(blank=True, max_length=250, null=True)),
                ('response_16', models.CharField(blank=True, max_length=250, null=True)),
                ('response_17', models.CharField(blank=True, max_length=250, null=True)),
                ('response_18', models.CharField(blank=True, max_length=250, null=True)),
                ('response_19', models.CharField(blank=True, max_length=250, null=True)),
                ('response_20', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_1', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_2', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_3', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_4', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_5', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_6', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_7', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_8', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_9', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_10', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_11', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_12', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_13', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_14', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_15', models.CharField(blank=True, max_length=250, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateJob', to='administrator.createjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to='user.applicant')),
            ],
            options={
                'db_table': 'AppliedJob',
            },
        ),
    ]
