# Generated by Django 3.1.1 on 2020-12-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_header', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'SavedJobs',
            },
        ),
    ]
