# Generated by Django 3.1.4 on 2021-05-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_1',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_10',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_11',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_12',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_13',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_14',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_15',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_2',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_3',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_4',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_5',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_6',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_7',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_8',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='requirement_9',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_11',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_12',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_13',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_14',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_15',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_16',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_17',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_18',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_19',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='response_20',
        ),
    ]
