# Generated by Django 3.1.1 on 2020-12-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201214_1308'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_header',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='requirement_11',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='requirement_12',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='requirement_13',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='requirement_14',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='requirement_15',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_11',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_12',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_13',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_14',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_15',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_16',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_17',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_18',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_19',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='response_20',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.createjob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.applicant'),
            preserve_default=False,
        ),
    ]
