# Generated by Django 3.1.1 on 2020-12-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20201212_1602'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjobs',
            name='job_description',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.CharField(blank=True, max_length=250, null=True)),
                ('response_2', models.CharField(blank=True, max_length=250, null=True)),
                ('response_3', models.CharField(blank=True, max_length=250, null=True)),
                ('response_4', models.CharField(blank=True, max_length=250, null=True)),
                ('response_5', models.CharField(blank=True, max_length=250, null=True)),
                ('response_6', models.CharField(blank=True, max_length=250, null=True)),
                ('response_7', models.CharField(blank=True, max_length=250, null=True)),
                ('response_8', models.CharField(blank=True, max_length=250, null=True)),
                ('response_9', models.CharField(blank=True, max_length=250, null=True)),
                ('response_10', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_1', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_2', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_3', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_4', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_5', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_6', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_7', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_8', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_9', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement_10', models.CharField(blank=True, max_length=250, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateJob', to='administrator.createjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to='user.applicant')),
            ],
            options={
                'db_table': 'AppliedJob',
            },
        ),
    ]
