# Generated by Django 3.1.1 on 2020-12-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201214_0951'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_header',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='user_id',
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.createjob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.applicant'),
            preserve_default=False,
        ),
    ]
