# Generated by Django 3.1.1 on 2020-12-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_header',
        ),
        migrations.AlterField(
            model_name='savedjobs',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.createjob'),
        ),
        migrations.AlterField(
            model_name='savedjobs',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applicant'),
        ),
    ]
