# Generated by Django 3.1.1 on 2020-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='job_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
