# Generated by Django 3.1.1 on 2020-12-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201213_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjobs',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='savedjobs',
            old_name='user_id',
            new_name='user',
        ),
    ]
