# Generated by Django 3.1.4 on 2021-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210523_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='response_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_5',
            field=models.TextField(null=True),
        ),
    ]
