# Generated by Django 3.1.1 on 2020-12-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_savedjobs_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
