# Generated by Django 3.1.4 on 2021-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210524_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='response_10',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_11',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_12',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_13',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_14',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_15',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_16',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_17',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_18',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_19',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_20',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_6',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_7',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_8',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='response_9',
            field=models.TextField(null=True),
        ),
    ]
